In [1]:
import pynlo
import numpy as np

In [4]:
# Parameters
fwhm = 0.18
wl = 1030
window = 10.0
gdd = 0
tod = 0
points = 2**10
frep = 1
epp = 50e-12
rnn_window = 10

pulse = pynlo.light.DerivedPulses.SechPulse(
    power=1,
    T0_ps=fwhm / 1.76,
    center_wavelength_nm=wl,
    time_window_ps=window,
    GDD=gdd,
    TOD=tod,
    NPTS=points,
    frep_MHz=frep,
    power_is_avg=False,
)
pulse.set_epp(epp)

print(pulse.AT.shape)

(1024,)


In [5]:
pulse_profile = pulse.AT

pulse_profile = pulse_profile / np.max(np.absolute(pulse_profile))
pulse_profile = np.repeat(pulse_profile[np.newaxis, :], rnn_window, axis=0)
print(pulse_profile.shape)

(10, 1024)


In [2]:
a = np.random.random((6, 8))
a

array([[0.33735885, 0.72479501, 0.34873675, 0.9268981 , 0.25384896,
        0.24708474, 0.98159019, 0.59216875],
       [0.77542916, 0.9973755 , 0.13863648, 0.96945037, 0.54940719,
        0.5907197 , 0.44591732, 0.48288143],
       [0.9594333 , 0.65642591, 0.11712933, 0.20632133, 0.08472911,
        0.04842405, 0.87552004, 0.6555771 ],
       [0.8837111 , 0.58083744, 0.61471251, 0.01902558, 0.34739133,
        0.34219721, 0.53492668, 0.31842147],
       [0.59489117, 0.74252064, 0.06946366, 0.41911112, 0.23969575,
        0.72576838, 0.93429236, 0.53402548],
       [0.6158788 , 0.08697156, 0.96197429, 0.48648084, 0.80525921,
        0.76999585, 0.42629124, 0.43837352]])

In [4]:
a[:2, :]

array([[0.33735885, 0.72479501, 0.34873675, 0.9268981 , 0.25384896,
        0.24708474, 0.98159019, 0.59216875],
       [0.77542916, 0.9973755 , 0.13863648, 0.96945037, 0.54940719,
        0.5907197 , 0.44591732, 0.48288143]])

In [3]:
a[2:4, :]

array([[0.9594333 , 0.65642591, 0.11712933, 0.20632133, 0.08472911,
        0.04842405, 0.87552004, 0.6555771 ],
       [0.8837111 , 0.58083744, 0.61471251, 0.01902558, 0.34739133,
        0.34219721, 0.53492668, 0.31842147]])

In [6]:
a[-2:, :]

array([[0.59489117, 0.74252064, 0.06946366, 0.41911112, 0.23969575,
        0.72576838, 0.93429236, 0.53402548],
       [0.6158788 , 0.08697156, 0.96197429, 0.48648084, 0.80525921,
        0.76999585, 0.42629124, 0.43837352]])